services:
  - type: web
    name: health-monitoring-login
    env: static
    staticPublishPath: ./
    envVars:
      - key: REACT_APP_API_URL
        value: https://health-monitoring-api.onrender.com
